const express=require('express')
const app=express()
const bp=require('body-parser')
const cors=require('cors')
app.use(cors({origin:'http://localhost:3000',credentials:true}))
app.use(bp.json())
const cookie=require('cookie-parser')
app.use(cookie())
const usermodel=require('./Model/UserModel')
const signup=require('./Controller/RegisterUser')
const signin=require('./Controller/LoginController')
const loginadmin=require("./Controller/LoginAdmin")
const protected=require('./Controller/UpdatedRoute')
app.use('/',signup)
app.use('/',signin)
app.use('/',loginadmin)
app.use('/',protected)
app.listen(5000,()=>console.log('server started'))